name: Flutter Build & Test

# Triggers the workflow on push or pull request events but only for the "main" branch
on:
  push:
    branches: [ "main" , "rework/ui"]
  pull_request:
    branches: [ "main" ,"rewoork/ui"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - uses: actions/checkout@v4

      # 2. Install Java (Required for Android builds)
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Key for solo devs: caches the Flutter SDK to speed up builds

      # 4. Get dependencies
      - run: flutter pub get

      # 4.5 GENERATE CODE (Add this step!)
      - name: Run Build Runner
        run: dart run build_runner build --delete-conflicting-outputs

      # 5. Check for linting errors (Best practice!)
      - run: flutter analyze

      # 6. Run tests (If you have them)
      - run: flutter test

      # 7. Build the APK (Just to prove it builds)
      - run: flutter build apk --debug
